apiVersion: compute.cloud.com/v1
kind: Ec2Instance
metadata:
  name: ec2instance-learning-02
  namespace: default
  labels:
    learning: issue-02
spec:
  instanceType: t3.micro
  amiId: ami-placeholder
  region: eu-central-1
